### ISSUE TITLE
Feature Request: add option for simply importing the server's public key

### ISSUE THREAD

**Issue by stdevel** [stdevel/ansible-collection-landscape#2]
Unless a CA is used, it would be handy to simply import the Landscape server's public key as `landscape-config` unfortunately misses this parameter 🤡 🤡 🤡 

Idea:

```yaml
- name: Store Landscape certificate
  ansible.builtin.shell: |
    set -o pipefail
    openssl s_client -showcerts -servername HOSTNAME -servername HOSTNAME -connect HOSTNAME:443 <<< "Q" | openssl x509 -pubcert -out /etc/landscape/landscape_server.crt
  args:
    executable: /bin/bash
    creates: /etc/landscape/landscape_server.crt
```
